spring:
  application:
    name: bugwise
  datasource:
    url: jdbc:postgresql://bugwise-bugwise.c.aivencloud.com:17987/defaultdb
    username: avnadmin
    password: AVNS_fQ2vFoJFXmRL4UvZUpY
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    hikari:
      connection-timeout: 600000
      maximum-pool-size: 15
      max-lifetime: 1800000
  main:
    allow-bean-definition-overriding: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: https://localhost:9200
      repositories:
        enabled: true
  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:29092
      group-id: bugwise-chat-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      acks: -1
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

security:
  jwt:
    secret-key: 3ddihwjb23i3ihnsijw093nbdjkojoskh3dsbiuejbdis337t26r3v474g2qbyh298
    expiration-time: 86400000